[mypy]
python_version = 3.12
mypy_path = app:engines/rta/src:engines/personnel/src:engines/b2b/src:cockpit
explicit_package_bases = True
ignore_missing_imports = True
disable_error_code = var-annotated, call-overload, attr-defined, assignment, arg-type, operator, call-arg, type-var, dict-item
exclude = (?x)(
    engines/b2b/src/main\.py
    | engines/personnel/src/main\.py
  )
